### ISSUE TITLE
Can't install model_training

### ISSUE THREAD

**Issue by CloseChoice** [LAION-AI/Open-Assistant#2878]
Since the commit https://github.com/LAION-AI/Open-Assistant/pull/2206 I can't install model_training anymore. It looks like we try to install `ray` from a private aws artifactory via `trlx`.

The error (while just trying to install trlx):
```bash
Collecting trlx@ git+https://github.com/CarperAI/trlx.git@v0.6.0
  Cloning https://github.com/CarperAI/trlx.git (to revision v0.6.0) to /tmp/pip-install-2_26mpi5/trlx_9eaa446e0cdf486eac6f5fef72af0f93
  Running command git clone --filter=blob:none --quiet https://github.com/CarperAI/trlx.git /tmp/pip-install-2_26mpi5/trlx_9eaa446e0cdf486eac6f5fef72af0f93
  Running command git checkout -q b7db6f9e74c7d8dc719255b27968d2994836957a
  Resolved https://github.com/CarperAI/trlx.git to commit b7db6f9e74c7d8dc719255b27968d2994836957a
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting ray@ https://ray-ci-artifact-branch-public.s3.amazonaws.com/42bb0357a6fb13e4994789c824f3623f32869ad8/tmp/artifacts/.whl/ray-3.0.0.dev0-cp310-cp310-manylinux2014_x86_64.whl
  ERROR: HTTP error 404 while getting https://ray-ci-artifact-branch-public.s3.amazonaws.com/42bb0357a6fb13e4994789c824f3623f32869ad8/tmp/artifacts/.whl/ray-3.0.0.dev0-cp310-cp310-manylinux2014_x86_64.whl
ERROR: Could not install requirement ray@ https://ray-ci-artifact-branch-public.s3.amazonaws.com/42bb0357a6fb13e4994789c824f3623f32869ad8/tmp/artifacts/.whl/ray-3.0.0.dev0-cp310-cp310-manylinux2014_x86_64.whl from https://ray-ci-artifact-branch-public.s3.amazonaws.com/42bb0357a6fb13e4994789c824f3623f32869ad8/tmp/artifacts/.whl/ray-3.0.0.dev0-cp310-cp310-manylinux2014_x86_64.whl (from trlx@ git+https://github.com/CarperAI/trlx.git@v0.6.0) because of HTTP error 404 Client Error: Not Found for url: https://ray-ci-artifact-branch-public.s3.amazonaws.com/42bb0357a6fb13e4994789c824f3623f32869ad8/tmp/artifacts/.whl/ray-3.0.0.dev0-cp310-cp310-manylinux2014_x86_64.whl for URL https://ray-ci-artifact-branch-public.s3.amazonaws.com/42bb0357a6fb13e4994789c824f3623f32869ad8/tmp/artifacts/.whl/ray-3.0.0.dev0-cp310-cp310-manylinux2014_x86_64.whl
```

cc @sanagno

**Comment by dwyatte** [comment]
> In the meantime you can install ray manually first.

Turns out this doesn't work because of the pinned version of trlx from git. We should be able to pin to https://github.com/CarperAI/trlx/commit/fa991ce244d2f6d1ff63f4348735b7d3e8e40b88 instead. Can someone confirm this version of trlx works?

**Comment by andreaskoepf** [comment]
Should be fixed by #2984

**Comment by CloseChoice** [comment]
I still get an installation error and the reason is that we need `transformers>=4.28` since we are using llama but [trlx just supports transformers versions up to `4.27.1`](https://github.com/CarperAI/trlx/blob/main/setup.cfg#L22)

**Comment by olliestanley** [comment]
> I still get an installation error and the reason is that we need `transformers>=4.28` since we are using llama (see [transformers release notes](https://github.com/huggingface/transformers/releases/tag/v4.28.0)) but [trlx just supports transformers versions up to `4.27.1`](https://github.com/CarperAI/trlx/blob/main/setup.cfg#L22)

It looks like the underlying issue which caused them to pin `transformers<=4.27.1` has already been fixed [here](https://github.com/CarperAI/trlx/pull/451). I have left a comment asking if they can remove this restriction.

**Comment by olliestanley** [comment]
@CloseChoice trlx has now merged the PR to unpin version
