### ISSUE TITLE
Task page makes several new_task requests during loading

### ISSUE THREAD

**Issue by Vechtomov** [LAION-AI/Open-Assistant#541]
Current behavior of fetching new task during page load is not deterministic. 
On my machine it makes 3 requests if page is loading for the first time and 2 requests on each next page open.
![requests](https://user-images.githubusercontent.com/28014244/211196612-26a8b95d-be0d-4d44-bb82-bdd621c53c46.png)
It's caused by this code block
```js
useEffect(() => {
  if (tasks.length == 0) {
    mutate();
  }
}, [tasks]);
```
As a solution, we can do this
```js
const { data: task, isLoading, mutate } = useSWRImmutable("/api/new_task/initial_prompt ", fetcher, {
  revalidateOnMount: true,
});
...
if (!task) {
  return isLoading 
    ? <LoadingScreen text="Loading..." /> 
    : <Container className="p-6 text-center text-gray-800">No tasks found...</Container>;
}
const tasks = [task];
```
But this solution requires auto-ACK which is yet under discussion in #520.
I can make a pr but it would be easier if you add me to the developers chat in discord.

**Comment by Klotske** [comment]
With PR #530 we've got `useGenericTaskAPI` hook that could solve this problem.
I think we need to rewrite pages in `create` and `evaluate` routes to implement it. This should fix this.

**Comment by Vechtomov** [comment]
It seems that `useGenericTaskAPI` doesn't fix fully the problem.
![label_requests](https://user-images.githubusercontent.com/28014244/211208183-07a6e925-f908-413c-be10-718f18075a39.png)
In production build page makes 2 requests on first load / reload.

**Comment by AbdBarho** [comment]
I have added a temporary solution in [#550 diff](https://github.com/LAION-AI/Open-Assistant/pull/550/files#diff-18bb5b39874e83bd72a02f2f7baa12b00dbf21187c5d42594ee1e61d1c0f0c4c)

We should test this thoroughly though, we don't want us to ddos our backend.

**Comment by AbdBarho** [comment]
Not the case anymore.
